(defun esta (numero) numero)
(defun prueba (num) (* (esta 5) 2))
(defun se (num) (+ (prueba 1) 10))
(defun ve (num) (- (se 1) 10))
(defun simple (num) (+ (ve 1) 80))
(defun pero (num) (- (simple 1) 80))
(defun pone (num) (+ (pero 1) 1))
(defun a (num) (/ (pone 1) 8))
(defun prueba (num) (* (a 1) 8))
(defun el (num) (- (prueba 1) 5))
(defun depth (num) (+ (el 1) 5))
(defun de (num) (/ (depth 1) 20))
(defun su (num) (* (de 1) 20))
(defun programa (num 1) (- (su) 3))
(defun y (num) (+ (programa 1) 3))
(defun eso (num) (/ (y 1) 5))
(defun me (num) (* (eso 1) 5))
(defun hace (num) (- (me 1) 1))
(defun feliz (num) (+ (hace 1) 1))
(feliz 1)
